{{- $nss := .Values.namespaces | default (list) -}}
{{- if not (has .Values.namespace $nss) -}}
{{- $nss = append $nss .Values.namespace -}}
{{- end -}}
{{- range $ns := $nss }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    openshift.io/cluster-monitoring: "true"
---
{{- end }}
