object-templates-raw: |
  {{hub- $cm := (lookup "v1" "ConfigMap" .PolicyMetadata.namespace (printf "%s.rendered-config" .ManagedClusterName)) | default dict hub}}
  {{hub- $config := (index ($cm.data | default dict) "config" | default "" | fromYaml | default dict) hub}}
  {{hub- $auth := (index (index $config "acs" | default dict) "auth" | default dict) hub}}
  {{hub- $authProvider := (index $auth "provider" | default "openshift") hub}}
  {{hub- $minimumRole := (index $auth "minimumRole" | default "None") hub}}
  {{hub- $adminGroup := (index $auth "adminGroup" | default "cluster-admins") hub}}
  {{hub- if $authProvider hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: acs-declarative-configs
        namespace: stackrox
      data:
        auth-provider.yaml: |
          name: OpenShift
          minimumRole: '{{hub $minimumRole hub}}'
          openshift:
            enable: true
          groups:
            - key: groups
              value: '{{hub $adminGroup hub}}'
              role: Admin
  {{hub- end hub}}
