object-templates-raw: |
  - complianceType: musthave
    objectDefinition:
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ScanSetting
      metadata:
        name: default
        namespace: openshift-compliance
      rawResultStorage:
        enabled: true
        {{hub- if (index .ManagedClusterLabels "autoshift.io/compliance-storage-class") hub}}
        storageClassName: '{{hub index .ManagedClusterLabels "autoshift.io/compliance-storage-class" hub}}'
        {{hub- end hub}}
