apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: governance-policy-framework-tuning
  namespace: open-cluster-management
spec:
  resourceRequirements:
  - containerID: deployments:governance-policy-framework:governance-policy-framework-addon
    resources:
      requests:
        memory: '{{hub index .ManagedClusterLabels "autoshift.io/acm-addon-gpf-mem-request" | default "128Mi" hub}}'
        cpu: '{{hub index .ManagedClusterLabels "autoshift.io/acm-addon-gpf-cpu-request" | default "100m" hub}}'
      limits:
        memory: '{{hub index .ManagedClusterLabels "autoshift.io/acm-addon-gpf-mem-limit" | default "512Mi" hub}}'
