object-templates-raw: |
  {{- $ingressDomain := (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: artifactory
        namespace: jfrog-system
      spec:
        host: artifactory.{{ $ingressDomain }}
        to:
          kind: Service
          name: openshiftartifactoryha-artifactory-ha-primary
          weight: 100
        port:
          targetPort: 8082
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect
