apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: anyuid
users:
- system:serviceaccount:openshift-operators:artifactory-ha-operator
- system:serviceaccount:jfrog-system:openshiftartifactoryha-artifactory-ha
