{{- if not (empty $.Values.hubClusterSets) }}
  {{- $policyNamespace := $.Values.policy_namespace }}
  {{- $policyName := "policy-cluster-configs" }}
  {{- $placementName := "placement-cluster-configs" }}
  {{- $configPolicyName := "policy-cluster-configs" }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ $policyNamespace }}
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $configPolicyName }}
          namespace: {{ $policyNamespace }}
        spec:
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            #Indentation Anchor
            {{ "{{" }} $allRendered := dict {{ "}}" }}
            {{ "{{-" }} $managedClusterLookupResult := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "") | default dict {{ "}}" }}
            {{ "{{-" }} $allClusterConfigs := (dict) {{ "}}" }}
            {{ "{{-" }} $allClusterSetConfigs := (dict) {{ "}}" }}
            {{ "{{-" }} $clusterConfigMaps := (lookup "v1" "ConfigMap" "" "" "autoshift.io/cluster-configs") | default dict {{ "}}" }}
            {{ "{{-" }} $clusterSetConfigMaps := (lookup "v1" "ConfigMap" "" "" "autoshift.io/cluster-set-configs") | default dict {{ "}}" }}
            {{ "{{-" }} $defaultConfigs := (dict) {{ "}}" }}
            {{ "{{-" }} $defaultConfigMaps := (lookup "v1" "ConfigMap" "" "" "autoshift.io/cluster-default-configs") | default dict {{ "}}" }}
            ##### DEFAULT CONFIG MAPS #####
            {{ "{{-" }} range $idx, $cm := $defaultConfigMaps.items {{ "}}" }}
                {{ "{{-" }} $_ := set $defaultConfigs $cm.metadata.namespace ((($cm).data).config | default "{}" | fromJson) {{ "}}" }}
            {{ "{{-" }} end {{ "}}" }}
            ##### CLUSTER SET CONFIG MAPS #####
            {{ "{{-" }} $seenClusterSetConfigs := (dict) {{ "}}" }}
            {{ "{{-" }} range $_, $clusterSetConfigMap := $clusterSetConfigMaps.items {{ "}}" }}
              {{ "{{-" }} $cm := $clusterSetConfigMap {{ "}}" }}
              {{ "{{-" }} if hasPrefix "cluster-set-config." $cm.metadata.name {{ "}}" }}
                {{ "{{-" }}  $clusterSetName := ($cm.metadata.name | replace "cluster-set-config." "")  {{ "}}" }}
                {{ "{{-" }} if (hasKey $seenClusterSetConfigs $clusterSetName) {{ "}}" }}
                  {{ "{{-" }} fail (printf "Duplicate cluster set config detected: ManagedClusterSet %s has multiple config maps!. ManagedClusterSet config maps must be unique across all namespaces!" ($cm.metadata.name | replace "cluster-set-config." "")) {{ "}}" }}
                {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} $_ := set $seenClusterSetConfigs $clusterSetName $cm.metadata.namespace {{ "}}" }}
                {{ "{{-" }} $clusterSetName := ($cm.metadata.name | replace "cluster-set-config." "") {{ "}}" }}
                {{ "{{-" }} if not (hasKey $allClusterSetConfigs $cm.metadata.namespace) {{ "}}" }}
                  {{ "{{-" }} $_ := set $allClusterSetConfigs $cm.metadata.namespace (dict) {{ "}}" }}
                {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} $clusterSetConfig := (index $clusterSetConfigMap.data "config" | default "{}" | fromJson) {{ "}}" }}
                {{ "{{-" }} $_ := set (index $allClusterSetConfigs $cm.metadata.namespace) $clusterSetName $clusterSetConfig{{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
            {{ "{{-" }} end {{ "}}" }}
            ##### CLUSTER CONFIG MAPS ####
            {{ "{{-" }} range $_, $clusterConfigMap := ($clusterConfigMaps.items | default list) {{ "}}" }}
              {{ "{{-" }} if hasPrefix "managed-cluster-config." $clusterConfigMap.metadata.name {{ "}}" }}
                {{ "{{-" }} $clusterConfig := (index $clusterConfigMap.data "config" | default "{}" | fromJson) {{ "}}" }}
                {{ "{{-" }} $clusterNs := $clusterConfigMap.metadata.namespace {{ "}}" }}
                {{ "{{-" }} $clusterName := ($clusterConfigMap.metadata.name | replace "managed-cluster-config." "") {{ "}}" }}
                {{ "{{-" }} $wrapper := (dict $clusterNs (dict $clusterName $clusterConfig)) {{ "}}" }}
                {{ "{{-" }} $allClusterConfigs = merge $wrapper $allClusterConfigs {{ "}}" }}
                {{ "{{-" }} $clusterSetName := ($clusterConfig.clusterSet | default "") {{ "}}" }}
                {{ "{{-" }} $clusterSetConfig := (dig $clusterNs $clusterSetName (dict) $allClusterSetConfigs )  {{ "}}" }}
                {{ "{{-" }} $defaultConfig := (index $defaultConfigs $clusterNs | default dict)  {{ "}}" }}
                {{ "{{-" }} $renderedConfig := (dict) {{ "}}" }}
                {{ "{{-" }} $_ := merge $renderedConfig $clusterConfig $clusterSetConfig $defaultConfig   {{ "}}" }}
                {{ "{{-" }} if not (hasKey $allRendered $clusterNs) {{ "}}" }}
                  {{ "{{-" }} $_ := set $allRendered $clusterNs (dict) {{ "}}" }}
                {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} $_ := set (index $allRendered $clusterNs) $clusterName $renderedConfig {{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
            {{ "{{-" }} end {{ "}}" }}
            {{ "{{-" }} range $_, $cluster := $managedClusterLookupResult.items {{ "}}" }}
              {{ "{{-" }} $clusterSetName := index ((($cluster).metadata).labels | default dict) "cluster.open-cluster-management.io/clusterset" | default ""  {{ "}}" }}
              {{ "{{-" }} $clusterSetNamespace  := (index $seenClusterSetConfigs $clusterSetName | default "")  {{ "}}" }}
              {{ "{{-" }} $clusterSetConfig := (dig $clusterSetNamespace $clusterSetName (dict) $allClusterSetConfigs) {{ "}}" }}
              {{ "{{-" }} $defaultConfig := (index $defaultConfigs $clusterSetNamespace | default dict) {{ "}}" }}
              {{ "{{-" }} if ne $clusterSetNamespace "" {{ "}}" }}
                {{ "{{-" }} $clusterConfig := (dig $clusterSetNamespace $cluster.metadata.name (dict) $allClusterConfigs) {{ "}}" }}
                {{ "{{-" }} $renderedConfig := (dict) {{ "}}" }}
                {{ "{{-" }} $_ := merge $renderedConfig $clusterConfig $clusterSetConfig $defaultConfig {{ "}}" }}
                {{ "{{-" }} $wrapper := (dict $clusterSetNamespace (dict $cluster.metadata.name $renderedConfig)) {{ "}}" }}
                {{ "{{-" }} $_ := merge $wrapper $allRendered {{ "}}" }}
                {{ "{{-" }} $allRendered = $wrapper {{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
            {{ "{{-" }} end {{ "}}" }}
            {{ if $.Values.debug | default false }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: cluster-config-debug
                  namespace: {{ $.Values.policy_namespace }}
                  labels:
                    autoshift.io/debug: ""
                data:
                  allRendered: |
                    {{ "{{" }} $allRendered | toYaml | autoindent {{ "}}" }}
            {{ end }}

            {{ "{{-" }} range $ns, $clusters := ($allRendered | default dict) {{ "}}" }}
              {{ "{{-" }} range $clusterName, $config := $clusters {{ "}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: {{ "{{" }} (printf "%s.%s" $clusterName "rendered-config") {{ "}}" }}
                  namespace: {{ "{{" }} $ns {{ "}}" }}
                  labels:
                    autoshift.io/rendered-config-map: ""
                data:
                  config: |
                    {{ "{{" }} $config | toYaml | autoindent {{ "}}" }}
              {{ "{{" }} end {{ "}}" }}
            {{ "{{" }} end {{ "}}" }}

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ $policyNamespace }}
spec:
  clusterSets:
    {{- range $clusterSet, $value := $.Values.hubClusterSets  }}
    - {{ $clusterSet }}
    {{- end }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ $policyNamespace }}
placementRef:
  name: {{ $placementName}}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy
{{- end }}
