object-templates-raw: |
  {{- $channel := "{{hub index .ManagedClusterLabels "autoshift.io/openshift-upgrade-channel" | default "" hub}}" }}
  {{- if ne $channel "" }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      metadata:
        name: version
      spec:
        channel: '{{ $channel }}'
  {{- end }}
