apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
spec:
  version: '{{hub index .ManagedClusterLabels "autoshift.io/servicemesh3operator-istio-version" | default "v1.28-latest" hub}}'
  profile: ambient
  namespace: istio-cni
  values:
    cni:
      ambient:
        reconcileIptablesOnStartup: true
