apiVersion: v1
kind: Secret
metadata:
  name: tempo-s3-secret
  namespace: tracing-system
type: Opaque
stringData:
  endpoint: https://{{ fromConfigMap "tracing-system" "tempo-bucket-odf" "BUCKET_HOST" }}:{{ fromConfigMap "tracing-system" "tempo-bucket-odf" "BUCKET_PORT" }}
  bucket: '{{ fromConfigMap "tracing-system" "tempo-bucket-odf" "BUCKET_NAME" }}'
  access_key_id: '{{ fromSecret "tracing-system" "tempo-bucket-odf" "AWS_ACCESS_KEY_ID" | base64dec }}'
  access_key_secret: '{{ fromSecret "tracing-system" "tempo-bucket-odf" "AWS_SECRET_ACCESS_KEY" | base64dec }}'
