object-templates-raw: |
  {{hub $cm := (lookup "v1" "ConfigMap" .PolicyMetadata.namespace (printf "%s.rendered-config" .ManagedClusterName)) | default dict hub}}
  {{hub $config := (index $cm "data" | default dict) hub}}
  {{hub $configYaml := (index $config "config" | default "" | fromYaml | default dict) hub}}
  {{hub $disconnected := (index $configYaml "disconnected" | default dict) hub}}
  {{hub $mirror := (index $disconnected "mirrorRegistry" | default dict) hub}}
  {{hub $mirrorHost := (index $mirror "host") hub}}
  {{hub $mirrorPath := (index $mirror "path" | default "") hub}}
  {{hub $url := $mirrorHost hub}}
  {{hub if $mirrorPath hub}}
  {{hub $url = (printf "%s/%s" $mirrorHost $mirrorPath) hub}}
  {{hub end hub}}
  {{hub $suffix := (index .ManagedClusterLabels "autoshift.io/mirror-catalog-suffix" | default "mirror") hub}}
  {{hub $catalogs := (index $disconnected "catalogs") hub}}
  {{hub range $_, $catalog := $catalogs hub}}
  {{hub $catName := (printf "%s-%s" (index $catalog "source") $suffix) hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        name: {{hub $catName hub}}
        namespace: openshift-marketplace
      spec:
        sourceType: grpc
        image: '{{hub printf "%s/%s:%s" $url (index $catalog "imagePath") (index $catalog "tag") hub}}'
        displayName: {{hub index $catalog "displayName" | default $catName hub}}
        publisher: {{hub index $catalog "publisher" | default "AutoShift" hub}}
        updateStrategy:
          registryPoll:
            interval: {{hub index $catalog "updateInterval" | default "10m" hub}}
  {{hub end hub}}
