object-templates-raw: |
  {{hub $cm := (lookup "v1" "ConfigMap" .PolicyMetadata.namespace (printf "%s.rendered-config" .ManagedClusterName)) | default dict hub}}
  {{hub $config := (index $cm "data" | default dict) hub}}
  {{hub $configYaml := (index $config "config" | default "" | fromYaml | default dict) hub}}
  {{hub $disconnected := (index $configYaml "disconnected" | default dict) hub}}
  {{hub $mirror := (index $disconnected "mirrorRegistry" | default dict) hub}}
  {{hub $mirrorHost := (index $mirror "host") hub}}
  {{hub $mirrorPath := (index $mirror "path" | default "") hub}}
  {{hub $url := $mirrorHost hub}}
  {{hub if $mirrorPath hub}}
  {{hub $url = (printf "%s/%s" $mirrorHost $mirrorPath) hub}}
  {{hub end hub}}
  {{hub $mirrors := (index $mirror "mirrors") hub}}
  {{hub $useIDMS := (index $disconnected "useIDMS" | default true) hub}}
  {{hub if (gt (len $mirrors) 0) hub}}
  {{hub if $useIDMS hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: config.openshift.io/v1
      kind: ImageDigestMirrorSet
      metadata:
        name: autoshift-disconnected-mirrors
      spec:
        imageDigestMirrors:
        {{hub range $_, $entry := $mirrors hub}}
        {{hub $source := (index $entry "source") hub}}
        {{hub $mirrorLoc := (index $entry "mirror" | default "") hub}}
        {{hub if $mirrorLoc hub}}
        {{hub $mirrorLoc = (printf "%s/%s" $mirrorHost $mirrorLoc) hub}}
        {{hub else hub}}
        {{hub $mirrorLoc = $url hub}}
        {{hub end hub}}
          - source: {{hub $source hub}}
            mirrors:
              - '{{hub $mirrorLoc hub}}'
        {{hub end hub}}
  {{hub else hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: operator.openshift.io/v1alpha1
      kind: ImageContentSourcePolicy
      metadata:
        name: autoshift-disconnected-mirrors
      spec:
        repositoryDigestMirrors:
        {{hub range $_, $entry := $mirrors hub}}
        {{hub $source := (index $entry "source") hub}}
        {{hub $mirrorLoc := (index $entry "mirror" | default "") hub}}
        {{hub if $mirrorLoc hub}}
        {{hub $mirrorLoc = (printf "%s/%s" $mirrorHost $mirrorLoc) hub}}
        {{hub else hub}}
        {{hub $mirrorLoc = $url hub}}
        {{hub end hub}}
          - source: {{hub $source hub}}
            mirrors:
              - '{{hub $mirrorLoc hub}}'
        {{hub end hub}}
  {{hub end hub}}
  {{hub end hub}}
  {{hub- $tagMirrors := (index $mirror "tagMirrors" | default list) hub}}
  {{hub if and $useIDMS (gt (len $tagMirrors) 0) hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: config.openshift.io/v1
      kind: ImageTagMirrorSet
      metadata:
        name: autoshift-disconnected-tag-mirrors
      spec:
        imageTagMirrors:
        {{hub range $_, $entry := $tagMirrors hub}}
        {{hub $source := (index $entry "source") hub}}
        {{hub $mirrorLoc := (index $entry "mirror" | default "") hub}}
        {{hub if $mirrorLoc hub}}
        {{hub $mirrorLoc = (printf "%s/%s" $mirrorHost $mirrorLoc) hub}}
        {{hub else hub}}
        {{hub $mirrorLoc = $url hub}}
        {{hub end hub}}
          - source: {{hub $source hub}}
            mirrors:
              - '{{hub $mirrorLoc hub}}'
        {{hub end hub}}
  {{hub end hub}}
