apiVersion: v1
kind: ConfigMap
metadata:
  name: ippool-internal
  namespace: '{{hub $.PolicyMetadata.namespace hub}}'
data:
  adv: IyBUaGlzIGlzIGFuIGV4YW1wbGUgSVBQb29sIGFkdmVydGlzZW1lbnQgY29uZmlndXJhdGlvbiBhbmQgZG9lcyBub3QgZ2V0IGFwcGxpZWQgdG8gdGhlIGNsdXN0ZXIKIyBBZGQgdGhlIG5hbWUgb2YgdGhpcyBmaWxlIHRvIHRoZSBtZXRhbGxiLWlwcG9vbCB2YWx1ZSB0byBhcHBseSB0aGlzIGNvbmZpZ3VyYXRpb24KIyBJZiB5b3UgbmFtZSB0aGlzIGZpbGUgImludGVybmFsLnlhbWwiLCB5b3VyIHZhbHVlIHNob3VsZCBiZSBtZXRhbGxiLWlwcG9vbC0qOiAnaW50ZXJuYWwnCmtpbmQ6IElQQWRkcmVzc1Bvb2wKYXBpVmVyc2lvbjogbWV0YWxsYi5pby92MWJldGExCm1ldGFkYXRhOgogIG5hbWU6IGludGVybmFsLWNpc2NvCiAgbmFtZXNwYWNlOiBtZXRhbGxiLXN5c3RlbQpzcGVjOgogICMgYXV0b0Fzc2lnbjogZmFsc2UgIFRvIHByZXZlbnQgSVBzIGZyb20gYmVpbmcgaGFuZGVkIG91dCBpZiBhbm90aGVyIHBvb2wgaXMgZXhoYXVzdGVkIGFuZCB0aGlzIGlzIHVzZWQgYXMgYmFja3VwCiAgYWRkcmVzc2VzOgogICAgLSAxOTIuMTY4LjEwMC4xLTE5Mi4xNjguMTAwLjIwCg==
