object-templates-raw: |
  {{hub- $l2_list := list hub}}
  {{hub- range $label, $labelvalue := .ManagedClusterLabels hub}}
    {{hub- if $label | hasPrefix "autoshift.io/metallb-l2-" hub}}
      {{hub- $l2_list = append $l2_list $labelvalue hub}}
    {{hub- end hub}}
  {{hub- end hub}}
  {{hub- range $l2_list hub}}
    {{hub- $cfg := ((lookup "v1" "ConfigMap" $.PolicyMetadata.namespace (print "l2-" .)).data) hub}}
  - complianceType: mustonlyhave
    objectDefinition:
      {{hub- if $cfg.adv hub}}
          {{hub $cfg.adv | base64dec | autoindent hub}}
        {{hub- end hub}}
      {{hub- end hub}}
