object-templates-raw: |
  {{hub- $peer_list := list hub}}
  {{hub- range $label, $labelvalue := .ManagedClusterLabels hub}}
    {{hub- if $label | hasPrefix "autoshift.io/metallb-peer-" hub}}
      {{hub- $peer_list = append $peer_list $labelvalue hub}}
    {{hub- end hub}}
  {{hub- end hub}}
  {{hub- range $peer_list hub}}
    {{hub- $cfg := ((lookup "v1" "ConfigMap" $.PolicyMetadata.namespace (print "peer-" .)).data) hub}}
  - complianceType: musthave
    objectDefinition:
      {{hub- if $cfg.adv hub}}
          {{hub $cfg.adv | base64dec | autoindent hub}}
        {{hub- end hub}}
      {{hub- end hub}}
