apiVersion: v1
kind: ResourceQuota
metadata:
  name: metallb-quota
  namespace: metallb-system
spec:
  hard:
    cpu: '{{hub index .ManagedClusterLabels "autoshift.io/metallb-quota-cpu" | default "100m" hub}}'
    memory: '{{hub index .ManagedClusterLabels "autoshift.io/metallb-quota-memory" | default "256Mi" hub}}'
