apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: artifactory-db-pooler-ro
  namespace: jfrog-system
spec:
  cluster:
    name: artifactory-db
  instances: '{{hub index .ManagedClusterLabels "autoshift.io/jfrog-db-pooler-instances" | default "2" | toInt hub}}'
  type: ro
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: '1000'
      default_pool_size: '50'
      min_pool_size: '10'
      reserve_pool_size: '10'
      server_reset_query: DISCARD ALL
      server_check_query: SELECT 1
      server_check_delay: '30'
      query_wait_timeout: '120'
  template:
    metadata:
      labels:
        app: artifactory-db-pooler
    spec:
      containers:
      - name: pgbouncer
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: artifactory-db-pooler
