apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-trident-storage-profiles
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
{{- if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{- end }}
  disabled: false
  dependencies:
    - name: policy-trident-storage-config
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-trident-storage-profile-creation
          namespace: "{{ .Values.policy_namespace }}"
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates-raw: |
            {{ "{{hub" }} $configs := index (index (fromConfigMap "{{ $.Values.policy_namespace }}" (print .ManagedClusterName ".rendered-config") "config" | default "" | fromYaml) "trident" | default dict) {{ "hub}}" }}
            {{ "{{hub" }} range $storage := $configs.storage {{ "hub}}" }}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: cdi.kubevirt.io/v1beta1
                kind: StorageProfile
                metadata:
                {{ "{{hub" }}- if eq $storage.defaultStorageClass "true" {{ "hub}}" }}
                  annotations:
                    snapshot.storage.kubernetes.io/is-default-class: "true"
                {{ "{{hub" }}- end {{ "hub}}" }}
                  name: "{{ "{{hub" }} $storage.storageClassName {{ "hub}}" }}"
                spec:
                  claimPropertySets:
                  - accessModes:
                      - ReadWriteMany
                    volumeMode: Block
            {{ "{{hub-" }} end {{ "hub}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-trident-storage-profiles
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/trident'
              operator: In
              values:
              - 'true'
            - key: 'autoshift.io/virt'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-trident-storage-profiles
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-trident-storage-profiles
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-trident-storage-profiles
    apiGroup: policy.open-cluster-management.io
    kind: Policy
