apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-db
  namespace: gitlab-system
spec:
  instances: '{{hub index .ManagedClusterLabels "autoshift.io/gitlab-db-instances" | default "2" | toInt hub}}'
  postgresql:
    parameters:
      max_connections: '200'
      shared_buffers: 512MB
      effective_cache_size: 1536MB
      work_mem: 8MB
  bootstrap:
    initdb:
      database: gitlabhq_production
      owner: gitlab
  storage:
    size: 50Gi
  resources:
    requests:
      cpu: '1'
      memory: 2Gi
    limits:
      cpu: '2'
      memory: 4Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-db
  namespace: gitlab-system
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: gitlab-db
  endpoints:
  - port: metrics
    interval: 30s
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitlab-db-allow
  namespace: gitlab-system
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: gitlab-db
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: gitlab-system
    ports:
    - port: 5432
      protocol: TCP
    - port: 9187
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-operators
    ports:
    - port: 8000
      protocol: TCP
