{{- range $clusterSet, $value := merge (dict) (deepCopy (.Values.hubClusterSets | default dict)) (deepCopy (.Values.managedClusterSets | default dict)) }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: {{ $clusterSet }}
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
{{- end }}
