apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: aap-bucket-odf
  namespace: ansible-automation-platform
spec:
  storageClassName: openshift-storage.noobaa.io
  generateBucketName: aap-bucket-odf
