apiVersion: v1
kind: Secret
metadata:
  name: s3-aap-odf
  namespace: ansible-automation-platform
type: Opaque
stringData:
  s3-access-key-id: '{{ fromSecret "ansible-automation-platform" "aap-bucket-odf" "AWS_ACCESS_KEY_ID" | base64dec }}'
  s3-secret-access-key: '{{ fromSecret "ansible-automation-platform" "aap-bucket-odf" "AWS_SECRET_ACCESS_KEY" | base64dec }}'
  s3-bucket-name: '{{ fromConfigMap "ansible-automation-platform" "aap-bucket-odf" "BUCKET_NAME" }}'
  s3-endpoint: https://{{ fromConfigMap "ansible-automation-platform" "aap-bucket-odf" "BUCKET_HOST" }}:{{ fromConfigMap "ansible-automation-platform" "aap-bucket-odf" "BUCKET_PORT" }}
