object-templates-raw: |
  {{- $existingSecret := (lookup "v1" "Secret" "gitlab-system" "gitlab-redis-password") | default dict }}
  {{- $existingData := ($existingSecret.data | default dict) }}
  {{- $existingPass := (index $existingData "redis-password" | default "") }}
  {{- if (empty $existingPass) }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-redis-password
        namespace: gitlab-system
      type: Opaque
      stringData:
        redis-password: {{ printf "gitlabRedis%s" "{{hub .ManagedClusterName hub}}" }}
  {{- end }}
