apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-remove-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    alertmanagerMain:
      nodeSelector: {}
      tolerations: []
    prometheusK8s:
      nodeSelector: {}
      tolerations: []
    prometheusOperator:
      nodeSelector: {}
      tolerations: []
    metricsServer:
      nodeSelector: {}
      tolerations: []
    kubeStateMetrics:
      nodeSelector: {}
      tolerations: []
    telemeterClient:
      nodeSelector: {}
      tolerations: []
    openshiftStateMetrics:
      nodeSelector: {}
      tolerations: []
    thanosQuerier:
      nodeSelector: {}
      tolerations: []
    monitoringPlugin:
      nodeSelector: {}
      tolerations: []
