apiVersion: pipelines.openshift.io/v1alpha1
kind: GitopsService
metadata:
  name: cluster
  namespace: '{{hub index .ManagedClusterLabels "autoshift.io/gitops-namespace" | default "openshift-gitops" hub}}'
spec:
  runOnInfra: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
  - effect: NoExecute
    key: node-role.kubernetes.io/infra
