object-templates-raw: |
  {{- $cores := 0 }}
  {{- range (lookup "v1" "Node" "" "").items }}
    {{- if hasKey .metadata.labels "node-role.kubernetes.io/infra" }}
      {{- if eq $cores 0 }}
        {{- $cores = (.status.capacity.cpu | toInt) }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- $maxPods := ("{{hub index .ManagedClusterLabels "autoshift.io/infra-max-pods" | default 250 hub}}" | toInt) }}
  {{- $systemReservedMemory := "{{hub index .ManagedClusterLabels "autoshift.io/infra-system-reserved-memory" | default "2Gi" hub}}" }}
  {{- $systemReservedCpu := "{{hub index .ManagedClusterLabels "autoshift.io/infra-system-reserved-cpu" | default "500m" hub}}" }}
  {{- $kubeReservedMemory := "{{hub index .ManagedClusterLabels "autoshift.io/infra-kube-reserved-memory" | default "1Gi" hub}}" }}
  {{- $kubeReservedCpu := "{{hub index .ManagedClusterLabels "autoshift.io/infra-kube-reserved-cpu" | default "500m" hub}}" }}
  {{- $evictionMemory := "{{hub index .ManagedClusterLabels "autoshift.io/infra-eviction-memory" | default "500Mi" hub}}" }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: KubeletConfig
      metadata:
        name: infra-node-config
      spec:
        machineConfigPoolSelector:
          matchLabels:
            pools.operator.machineconfiguration.openshift.io/infra: ""
        kubeletConfig:
          podsPerCore: {{ add 1 (div $maxPods $cores) }}
          maxPods: {{ $maxPods }}
          systemReserved:
            memory: {{ $systemReservedMemory }}
            cpu: {{ $systemReservedCpu }}
          kubeReserved:
            memory: {{ $kubeReservedMemory }}
            cpu: {{ $kubeReservedCpu }}
          evictionHard:
            memory.available: {{ $evictionMemory }}
