apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-openshift-service-ca
  namespace: gitlab-system
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-objectstorage
  namespace: gitlab-system
spec:
  generateBucketName: gitlab
  storageClassName: openshift-storage.noobaa.io
