object-templates-raw: |
  {{hub- $configs :=  index (index (fromConfigMap .PolicyMetadata.namespace (print .ManagedClusterName ".rendered-config") "config" | default "" | fromYaml) "trident" | default dict) hub}}
  {{hub- range $idx, $storage := ($configs).storage hub}}
    {{hub- if or (eq (($storage).authMethod | default "password") "cert") (eq (($storage).authMethod | default "password") "certs") hub}}
  - complianceType: mustonlyhave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: {{hub $storage.secretName hub}}
        namespace: trident
      type: Opaque
      stringData:
        clientPrivateKey: {{ fromSecret "openshift-config" "api-tls" "tls.key" }}
    {{hub- else if (eq (($storage).authMethod | default "password") "password") hub}}
  - complianceType: mustonlyhave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: {{hub $storage.secretName hub}}
        namespace: trident
      type: Opaque
      data:
        username: {{hub fromSecret $storage.secretNamespace $storage.secretName "username" hub}}
        password: {{hub fromSecret $storage.secretNamespace $storage.secretName "password" hub}}
    {{hub- else hub}}
     {{hub- fail (printf "Unsupported auth method: \"%s\"; supported values are '(cert|certs)' or 'password'") hub}}
    {{hub- end hub}}
  {{hub- end hub}}
