apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  IPv6: false
  debug: true
  nodePrep: []
  imagePullSecrets: []
  imageRegistry: ''
  namespace: trident
  silenceAutosupport: false
