object-templates-raw: |
  {{- $configMaps := (lookup "v1" "ConfigMap" "" "" "autoshift.io/rendered-config-map") | default dict }}
  {{- range $_, $cm := ($configMaps.items | default list) }}
    {{- $clusterName := (replace ".rendered-config" "" $cm.metadata.name) }}
    {{- $mc := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" $clusterName) | default dict }}
    {{- $mcOwningNs := dig "metadata" "labels" "autoshift.io/owning-namespace" "" $mc }}
    {{- $config := ($cm.data.config | fromYaml) }}
    {{- $ci := (index $config "clusterInstall" | default dict) }}
    {{- $platform := (index $ci "platform" | default "baremetal") }}
    {{- if and (eq (index $ci "createCluster" | default "") "true") (or (empty $mc) (eq $mcOwningNs $cm.metadata.namespace)) }}
      {{- $secretSourceNs := (index $ci "secretSourceNamespace" | default "cluster-install-secrets") }}
      {{- if eq $platform "baremetal" }}
      {{- $defaultBmcCred := (index $ci "bmcCredentialRef" | default "default-bmc-cred") }}
      {{- $hosts := (index $config "hosts") }}
      {{- range $hostname, $host := $hosts }}
        {{- $bmcRef := (index $host "bmcCredentialRef" | default dict) }}
        {{- $bmcSecretName := (index $bmcRef "name" | default $defaultBmcCred) }}
        {{- $bmcSecretNs := (index $bmcRef "namespace" | default $secretSourceNs) }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: {{ $hostname }}-bmc-cred
        namespace: {{ $clusterName }}
      data: '{{ copySecretData $bmcSecretNs $bmcSecretName | toLiteral }}'
      {{- end }}
      {{- end }}
      {{- if eq $platform "baremetal" }}
      {{- $pullSecretRef := (index $ci "pullSecretRef" | default "default-pull-secret") }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: {{ $clusterName }}-pull-secret
        namespace: {{ $clusterName }}
      data: '{{ copySecretData $secretSourceNs $pullSecretRef | toLiteral }}'
      {{- end }}
    {{- end }}
  {{- end }}
