apiVersion: monitoring.openshift.io/v1
kind: AlertRelabelConfig
metadata:
  name: suppress-noobaa-pdb-at-limit
  namespace: openshift-monitoring
spec:
  configs:
  - sourceLabels:
    - alertname
    - namespace
    - poddisruptionbudget
    regex: PodDisruptionBudgetAtLimit;openshift-storage;noobaa-db-pg-cluster-primary
    action: Drop
