object-templates-raw: |
  {{hub- $clusterName := .ManagedClusterName hub}}
  {{hub- $policyNs := .PolicyMetadata.namespace hub}}
  {{hub- $rcm := (lookup "v1" "ConfigMap" $policyNs (printf "%s.rendered-config" .ManagedClusterName)) | default dict hub}}
  {{hub- $rcConfig := (index ($rcm.data | default dict) "config" | default "" | fromYaml | default dict) hub}}
  {{hub- $autoshiftConfigs := (index $rcConfig "managedAutoshift" | default list) hub}}
  {{hub- range $autoshiftConfig := $autoshiftConfigs hub}}
  {{hub- $appName := index $autoshiftConfig "appName" | default $clusterName hub}}
  {{hub- if (le (len $appName) 11) hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{hub print "policies-" $appName hub}}
        labels:
          autoshift.io/createdByAutoshift: "true"
          openshift.io/cluster-monitoring: "true"
  {{hub- end hub}}
  {{hub- end hub}}
