object-templates-raw: |
  {{hub- $clusterName := .ManagedClusterName hub}}
  {{hub- $policyNs := .PolicyMetadata.namespace hub}}
  {{hub- $rcm := (lookup "v1" "ConfigMap" $policyNs (printf "%s.rendered-config" .ManagedClusterName)) | default dict hub}}
  {{hub- $rcConfig := (index ($rcm.data | default dict) "config" | default "" | fromYaml | default dict) hub}}
  {{hub- $autoshiftConfigs := (index $rcConfig "managedAutoshift" | default list) hub}}
  {{hub- range $autoshiftConfig := $autoshiftConfigs hub}}
  {{hub- $appName := index $autoshiftConfig "appName" | default $clusterName hub}}
  {{hub- $gitopsNamespace := index $autoshiftConfig "gitopsNamespace" | default "openshift-gitops" hub}}
  {{hub- $useRepoSecret := index $autoshiftConfig "useRepoSecret" | default false hub}}
  {{hub- $valuesRepoUrl := index $autoshiftConfig "valuesRepoUrl" | default "" hub}}
  {{hub- if (and $useRepoSecret (le (len $appName) 11)) hub}}
  {{hub- $secretRef := index $autoshiftConfig "repoSecretRef" | default dict hub}}
  {{hub- $secretName := index $secretRef "name" | default "autoshift-repo-secret" hub}}
  {{hub- $secretNamespace := index $secretRef "namespace" | default $policyNs hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: repo-{{hub $appName hub}}
        namespace: {{hub $gitopsNamespace hub}}
        labels:
          argocd.argoproj.io/secret-type: repository
      data: '{{hub copySecretData $secretNamespace $secretName hub}}'
  {{hub- if (ne $valuesRepoUrl "") hub}}
  {{hub- $valuesSecretRef := index $autoshiftConfig "valuesRepoSecretRef" | default dict hub}}
  {{hub- $valuesSecretName := index $valuesSecretRef "name" | default "autoshift-values-repo-secret" hub}}
  {{hub- $valuesSecretNamespace := index $valuesSecretRef "namespace" | default $policyNs hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: repo-{{hub $appName hub}}-values
        namespace: {{hub $gitopsNamespace hub}}
        labels:
          argocd.argoproj.io/secret-type: repository
      data: '{{hub copySecretData $valuesSecretNamespace $valuesSecretName hub}}'
  {{hub- end hub}}
  {{hub- end hub}}
  {{hub- end hub}}
