object-templates-raw: |
  {{hub- range (fromConfigMap .PolicyMetadata.namespace "stig-remediation" "ocp4-stig" | trim | split "\n") hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ComplianceRemediation
      metadata:
        name: {{hub . hub}}
        namespace: openshift-compliance
      spec:
        apply: true
  {{hub- end hub}}

  {{hub- range (fromConfigMap .PolicyMetadata.namespace "stig-remediation" "rhcos4-stig" | trim | split "\n") hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ComplianceRemediation
      metadata:
        name: {{hub . hub}}
        namespace: openshift-compliance
      spec:
        apply: true
  {{hub- end hub}}
