object-templates-raw: |
  - complianceType: mustonlyhave
    objectDefinition:
      apiVersion: aap.ansible.com/v1alpha1
      kind: AnsibleAutomationPlatform
      metadata:
        name: "aap"
        namespace: "ansible-automation-platform"
      spec:
        controller:
          disabled: false
        hub:
          disabled: {{hub index .ManagedClusterLabels "autoshift.io/aap-hub-disabled" | default "false" hub}}
          {{hub- if eq (index .ManagedClusterLabels "autoshift.io/aap-file-storage" | default "false") "true" hub}}
          storage_type: {{hub index .ManagedClusterLabels "autoshift.io/aap-storage-type" | default "file" hub}}
          file_storage_size: 10Gi
          file_storage_storage_class: {{hub index .ManagedClusterLabels "autoshift.io/aap-file_storage_storage_class" | default "ocs-storagecluster-cephfs" hub}}
          {{hub- else if eq (index .ManagedClusterLabels "autoshift.io/aap-noobaa-s3-storage" | default "false") "true" hub}}
          storage_type: S3
          object_storage_s3_secret: s3-aap-odf
          {{hub- end hub}}
        eda:
          disabled: {{hub index .ManagedClusterLabels "autoshift.io/aap-eda-disabled" | default "true" hub}}
        lightspeed:
          disabled: {{hub index .ManagedClusterLabels "autoshift.io/aap-lightspeed-disabled" | default "true" hub}}
        redis_mode: standalone
        {{hub- if or (eq (index .ManagedClusterLabels "autoshift.io/aap-noobaa-s3-storage" | default "false") "true") (eq (index .ManagedClusterLabels "autoshift.io/aap-custom-cabundle" | default "false") "true") hub}}
        bundle_cacert_secret: user-ca-bundle
        {{hub- end hub}}
